version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: always
    ports:
      - 2000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DB_URL: postgresql://postgres:1234@db:5432/postgres
    depends_on:
      - db
      - redis

volumes:
  redis_data:
  db_data:
