version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      DB_URL: postgresql://postgres:1234@localhost:5432/postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'

volumes:
  redis_data:
  db_data:
