import { Model } from 'sequelize-typescript';
import {
  AutoIncrement,
  BelongsTo,
  Column,
  CreatedAt,
  DataType,
  ForeignKey,
  PrimaryKey,
  Table,
  UpdatedAt,
} from 'sequelize-typescript';
import { RequestCreatingAttributes } from '../interfaces/request.create';
import { User } from 'src/users/entities/user.entity';

@Table({
  tableName: 'requests',
  timestamps: true,
  defaultScope: { where: { active: true } },
})
export class Request extends Model<Request, RequestCreatingAttributes> {
  @PrimaryKey
  @AutoIncrement
  @Column({ type: DataType.BIGINT })
  declare id: number;
  @Column({ type: DataType.STRING, allowNull: false })
  declare title: string;
  @Column({ type: DataType.STRING, allowNull: false, unique: true })
  declare email: string;
  @ForeignKey(() => User)
  @Column({ type: DataType.BIGINT })
  declare userId: number;
  @Column({ type: DataType.STRING })
  declare subject: string;
  @Column({ type: DataType.STRING })
  declare message: string;
  @Column({ type: DataType.BOOLEAN, defaultValue: true })
  declare active: boolean;
  @CreatedAt
  @Column({ type: DataType.DATE })
  declare createdAt: Date;
  @UpdatedAt
  @Column({ type: DataType.DATE })
  declare updatedAt: Date;

  @BelongsTo(() => User)
  user: User;
}

// "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
// 	"name" VARCHAR(255) NOT NULL,
// 	"email" VARy
// CHAR(255) NOT NULL,
// 	"subject" VARCHAR(255),
// 	"message" TEXT,
// 	"active" BOOLEAN DEFAULT true,
// 	"createdAt" TIMESTAMP DEFAULT current_timestamp,
// 	"updatedAt" TIMESTAMP,
// 	"user_id" BIGINT,
