
CREATE type ROLES as ENUM ('USER', 'ADMIN');
CREATE TABLE "users" (
	"id" BIGSERIAL NOT NULL UNIQUE,
	"first_name" VARCHAR(255),
	"last_name" VARCHAR(255),
	"email" VARCHAR(255) NOT NULL,
	"age" INT ,
	"role" ROLES DEFAULT 'USER',
	"isActive" BOOLEAN DEFAULT true,
	"refreshToken" VARCHAR ,
	"createdAt" TIMESTAMP DEFAULT current_timestamp,
	"uodated_At" TIMESTAMP,
	PRIMARY KEY("id")
);
CREATE INDEX "users_index_0"
ON "users" ("first_name", "last_name", "email", "isActive", "role");

CREATE TABLE "requests" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"subject" VARCHAR(255),
	"message" TEXT,
	"active" BOOLEAN DEFAULT true,
	"createdAt" TIMESTAMP DEFAULT current_timestamp,
	"updatedAt" TIMESTAMP,
	"user_id" BIGINT,
	PRIMARY KEY("id")
);
CREATE INDEX "requests_index_0"
ON "requests" ("name", "email", "subject");

ALTER TABLE "requests"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;